---
- name: display ansible facts
  hosts: myhosts
  gather_facts: yes 
  tasks:
    - name: display ansible facts
      debug: 
        msg: >-
          os_family: {{ansible_facts.os_family}},
          distro: {{ansible_facts.distribution}},
          kernel:  {{ansible_facts.kernel}}
          # everything: {{ansible_facts}}
      
    - name: display debug 
      debug: var=ansible_facts 
...
 

